CREATE PROCEDURE FATURAMENTO_DEPARTAMENTO (@DATA_INICIAL DATE, @DATA_FINAL DATE)
AS
BEGIN
DECLARE @DEPARTAMENTO TABLE (SABOR VARCHAR(20), DEPARTAMENTO VARCHAR(20))
INSERT INTO @DEPARTAMENTO 
SELECT DISTINCT SABOR, 'FRUTAS NÃO CÍTRICAS' as DEPARTAMENTO 
FROM [TABELA DE PRODUTOS] WHERE 
SABOR IN ('Açai','Cereja','Cereja/Maça','Maça','Manga','Maracujá','Melância')
UNION
SELECT DISTINCT SABOR, 'FRUTAS CÍTRICAS' as DEPARTAMENTO 
FROM [TABELA DE PRODUTOS] WHERE 
SABOR IN ('Laranja','Uva','Limão','Morango','Morango/Limão','Lima/Limão')
SELECT D.[DEPARTAMENTO]
, SUM(I.QUANTIDADE * I.[PREÇO]) AS FATURAMENTO
FROM [TABELA DE PRODUTOS] P
INNER JOIN [ITENS NOTAS FISCAIS] I
ON P.[CODIGO DO PRODUTO] = I.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] N
ON N.NUMERO = I.NUMERO
INNER JOIN @DEPARTAMENTO D
ON P.SABOR = D.SABOR
WHERE N.DATA >= @DATA_INICIAL AND N.DATA <= @DATA_FINAL
GROUP BY D.[DEPARTAMENTO]
END;

EXEC FATURAMENTO_DEPARTAMENTO '2016-01-01','2016-01-15';