DECLARE @NOME VARCHAR(200)

DECLARE FUNCIONARIO_CURSOR CURSOR FOR SELECT NOME FROM FUNCIONARIOS
OPEN FUNCIONARIO_CURSOR
FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @NOME
WHILE @@FETCH_STATUS = 0
BEGIN
   PRINT 'Nome' + @NOME
   FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @NOME
END;

CLOSE FUNCIONARIO_CURSOR;
DEALLOCATE FUNCIONARIO_CURSOR;