DECLARE @VENDEDOR_ALEATORIO VARCHAR(12);
DECLARE @VAL_INICIAL INT;
DECLARE @ALEATORIO INT;
DECLARE @VAL_FINAL INT;
DECLARE @CONTADOR INT;
SET @VAL_INICIAL = 1;
SET @CONTADOR = 1;
SELECT @VAL_FINAL = COUNT(*) FROM [TABELA DE VENDEDORES];
SET @ALEATORIO = DBO.NUMERO_ALEATORIO(@VAL_INICIAL, @VAL_FINAL);
DECLARE CURSOR1 CURSOR FOR SELECT MATRICULA FROM [TABELA DE VENDEDORES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @VENDEDOR_ALEATORIO
WHILE @CONTADOR < @ALEATORIO
BEGIN
   FETCH NEXT FROM CURSOR1 INTO @VENDEDOR_ALEATORIO
   SET @CONTADOR = @CONTADOR + 1
END;
CLOSE CURSOR1;
DEALLOCATE CURSOR1;
SELECT @VENDEDOR_ALEATORIO, @ALEATORIO;
SELECT * FROM [TABELA DE VENDEDORES];