CREATE FUNCTION FATURAMENTO_BAIRRO (@BAIRRO VARCHAR(50))
RETURNS FLOAT
AS
BEGIN
   DECLARE @FATURAMENTO FLOAT
   SELECT @FATURAMENTO = SUM (I.QUANTIDADE * I.[PREÇO])
   FROM [ITENS NOTAS FISCAIS] I
   INNER JOIN [NOTAS FISCAIS] N
   ON I.NUMERO = N.NUMERO
   INNER JOIN [TABELA DE CLIENTES] C
   ON C.CPF = N.CPF
   WHERE C.BAIRRO = @BAIRRO
   RETURN @FATURAMENTO
END;

SELECT BAIRRO , DBO.FATURAMENTO_BAIRRO(BAIRRO) AS FATURAMENTO FROM [TABELA DE CLIENTES] WHERE BAIRRO = 'Jardins';